# Generated by Django 4.2.5 on 2023-10-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='qwerty', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
